// Downloads the site's web fonts from Google Fonts into public/fonts and writes
// src/styles/fonts.css, so the fonts are served from this origin: one less third
// party, preloadable, and reachable where fonts.googleapis.com is not.
//
//   node scripts/fetch-fonts.mjs
//
// Latin and Latin Extended subsets only for the Latin families. The Chinese
// families are fetched as `text=` subsets holding just the glyphs the site sets in
// display sizes (the name, the seals, the chapter numerals). The full Noto Serif SC
// used by the Chinese interface stays on Google Fonts, loaded on demand.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0 Safari/537.36';
const OUT = path.resolve('public/fonts');
const CSS_OUT = path.resolve('src/styles/fonts.css');
const SUBSETS = new Set(['latin', 'latin-ext']);
const DISPLAY_GLYPHS = '沈亦旸印壹贰叁肆伍陆柒捌玖水土';

const families = [
  { slug: 'fraunces', query: 'family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,100..900,0..100,0..1;1,9..144,100..900,0..100,0..1' },
  { slug: 'instrument-sans', query: 'family=Instrument+Sans:ital,wght@0,400..700;1,400..700' },
  { slug: 'jetbrains-mono', query: 'family=JetBrains+Mono:wght@400..500' },
  { slug: 'noto-serif-sc-display', query: `family=Noto+Serif+SC:wght@200..900&text=${encodeURIComponent(DISPLAY_GLYPHS)}`, text: true },
];

await mkdir(OUT, { recursive: true });
let css = '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n';
for (const family of families) {
  const res = await fetch(`https://fonts.googleapis.com/css2?${family.query}&display=swap`, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${family.slug}: ${res.status}`);
  const text = await res.text();
  const blocks = [...text.matchAll(/(?:\/\* (\S+) \*\/\s*)?@font-face \{([^}]+)\}/g)];
  let n = 0;
  for (const [, subset, body] of blocks) {
    if (!family.text && subset && !SUBSETS.has(subset)) continue;
    const url = body.match(/url\(([^)]+)\)/)?.[1];
    const style = body.match(/font-style: (\w+)/)?.[1] ?? 'normal';
    const weight = body.match(/font-weight: ([\d ]+)/)?.[1] ?? '400';
    const range = body.match(/unicode-range: ([^;]+);/)?.[1];
    const name = body.match(/font-family: '([^']+)'/)?.[1];
    if (!url || !name) continue;
    const file = `${family.slug}-${style}-${weight.replace(/\s+/g, '-')}${subset ? `-${subset}` : ''}.woff2`;
    const font = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!font.ok) throw new Error(`${file}: ${font.status}`);
    await writeFile(path.join(OUT, file), Buffer.from(await font.arrayBuffer()));
    css += `@font-face {\n  font-family: '${name}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n${range ? `  unicode-range: ${range};\n` : ''}}\n`;
    n++;
    console.log(file, (await import('node:fs')).statSync(path.join(OUT, file)).size, 'bytes');
  }
  if (!n) throw new Error(`${family.slug}: no faces matched`);
}
await writeFile(CSS_OUT, css);
console.log('wrote', CSS_OUT);
